Multiple currency support
unchainedshop/unchained pull request #271
Opened 2020-11-19 19:46 UTC by Mikearaya

2020-12-04 10:01 UTC, pozylon requested changes
Very good job, yet we can optimize this quite a bit so it feels good in all cases.

2020-12-04 10:01 UTC, pozylon commented on packages/core-pricing/plugins/product-price-fiat-crypto-exchange.js
> +    if (!productPrice || !productPrice?.amount) return null;
See ECB plugin, same comments apply

2020-12-04 10:08 UTC, pozylon commented
As pricing plugins get chained and hand over results it's very important that you don't return null. If you return null in a pricing plugin it means to cut the chain, which might not be desired, assuming you have these plugins activated and you want the following:

Pricing calculation for price in BTC:
1. Catalog Price (sort 0) -> results in no price because catalog price not there
2. ECB Plugin -> results in no price because EUR price not there
3. Coinbase Plugin -> results in a price because default currency CHF and Coinbase can do CHF -> BTC
4. Round to 50
5. Calculate VAT for Switzerland

2020-12-07 14:44 UTC, Mikearaya commented on packages/core-pricing/plugins/product-price-EUR-fiat-exchange.js
> +    if (!EURprice || !EURprice?.amount) return null;
i think 2 is already done with the line ` if (!EURprice || !EURprice?.amount) return null;` which will be change now based on remark 1 to  `if (!EURprice || !EURprice?.amount) super.calculate();`

2020-12-07 14:49 UTC, pozylon commented on packages/core-pricing/plugins/product-price-EUR-fiat-exchange.js
> +    if (!EURprice || !EURprice?.amount) return null;
Yeah but you should check this.calculation too

2020-12-07 15:23 UTC, Mikearaya commented
@pozylon I agree it would be nice if round to the next 50 is a plugin on its on so anyone can use it when needed, but an issue comes once added and the rounding is needed only for certain currency type/s but not on others. eg. users might not want to round to the next 50 when the currency is in crypto because there is a significant difference when doing that but they may want to round to the next 50 on fiat currency.
so unless we disable rounding when currency is crypto-based explicitly there is no other way to disable this once the plugin is enabled. what is your thought on this? 
FYI I've extracted the logic into its own plugin already but I thought of this issue

2020-12-07 15:52 UTC, pozylon commented
That is a very good point, maybe we could configure the rounding plugin? So like:

```
import RoundPlugin from 'meteor/unchained:core-pricing/plugins/round';

RoundPlugin.configure({
  "BTC": { "precision": 5000, "mercantile": false },
}) // only btc rounded to 5000 sats
```

or something like this, and all non

2020-12-09 22:53 UTC, Mikearaya commented
for the product price rounding plugin configurable approach. now can do it like this...
it's just really a draft to make sure if we are on the same page.
```
import { ProductPricingDirector } from 'meteor/unchained:core-pricing';
import ProductPriceRound from './product-price-round';

ProductPriceRound.configure({ currency: 'USD', precision: 100 });
ProductPriceRound.configure({ currency: 'default', precision: 50 });

ProductPricingDirector.registerAdapter(ProductPriceRound);
```

2020-12-17 20:45 UTC, pozylon approved these changes
Very good! I only have found some very small things. I think we should provide some documentation about the available pricing plugins at some point.

2020-12-17 20:45 UTC, pozylon commented on packages/core-pricing/plugins/product-price-coinbase-exchange.js
> +  static label = 'Convert EUR to crypto with curreny exchange rate';
This plugin is not restricted to EUR isn't it? It's more like "Convert Default Currency to Crypto...."

2020-12-17 20:45 UTC, pozylon commented on packages/core-pricing/plugins/product-price-coinbase-exchange.js
> +  const { data } = await cache.get(`${base}-${target}`, () =>
ECB rates can be cached for 24h I thought, maybe define here specifically rather than the default 60s

2020-12-17 21:37 UTC, Mikearaya commented
we definitely need to provide documentation for the pricing, I'll add it under configuration and i think the rounding plugin will be good for example.

2020-12-18 05:06 UTC, merged