Add range filter to workQueue #338
unchainedshop/unchained pull request #341
Opened 2021-03-26 19:56 UTC by Mikearaya

2021-03-30 13:21 UTC, pozylon requested changes
Good work!

2021-03-30 13:21 UTC, pozylon commented on packages/core-worker/director.js
> +    endDate = new Date(),
I'd go the other way round, default startDate to new Date(0) and then check if endDate is set or not, it makes it more clear for developers that the query will always fetch from the beginning if no explicit end or start date is set, an end date of new Date() could interfere with minor time differences, polling logic and such and throw up questions if that is safe to do so even though it is.

2021-03-31 16:57 UTC, Mikearaya commented on packages/api/schema/query.js
> +        startDate: Date
I agree it is more descriptive this way and we can use it as a standard on other range filters to.

2021-04-15 09:58 UTC, pozylon commented
@Mikearaya Ready for another review?

2021-04-15 09:59 UTC, pozylon approved these changes

2021-04-15 09:59 UTC, merged