Create cart on sign up and enrolment #312
unchainedshop/unchained pull request #344
Opened 2021-03-29 11:24 UTC by Mikearaya

2021-03-30 14:39 UTC, pozylon requested changes
Not so happy about this one:

1. it doesn't feel like mutations is the right abstraction layer to add this function, we should propably have an Orders.ensureCartForUser() function that we can call at various places more in the core of unchained. For login creating methods, the hook where we Orders.migrateCart is kind of the right place, for situations where a cart becomes an order (can happen even when a checkout function throws and also when carts get removed)
2. This could be a breaking behavior for some customers and maybe even limit some use cases, in some situations clients use "createCart" mutation to set an arbitrary orderNumber for example. So I think while it's okay to make it a default to ensure having carts on users, we should provide a "settings" parameter to disable this feature
3. We need a bootup call to ensure cart creation for all currently existing users when this feature is first activated
4. With this feature activated, we will propably have much more "dead" carts because of guest logins creating carts and that is linked to #332. To tackle that, we should remove guests after a while and make sure cart invalidation is optimized (see ticket #332 for that).

I propose to take care of 1, 2 & 3 but then kind of tag the feature "experimental" so it's only the default when some sort of experimental environment variable is set to some flag. That way we already have the feature and we can find solutions together with the needed cleanup and invalidation changes for guests and orders.

2021-03-30 14:53 UTC, pozylon commented
@Mikearaya I started to work on a stale user removal plugin a while ago but didn't continue:

https://github.com/unchainedshop/unchained/pull/296

2021-04-04 18:58 UTC, Mikearaya commented
@pozylon I have add the changes for 1, 2 & 3 like discussed above now there is a environment variable `ENSURE_USER_HAS_CART` required enable this feature and also a setting parameter  `assignCartForUsers` boolean value that can be passed on engine start up to enable cart creation for existing users in a system (default to false).

2021-04-06 06:37 UTC, pozylon requested changes
The first time I have reviewed the PR, you have added `await getCart` to various mutations now this is gone and we have a dedicated Orders.ensureCartForUser function and it looks like that function gets called on checkout and on boot and it has been done in a way that is compatible with the webhooks and subscription logic, but now the function seems not to get called anymore when a login token gets created, cart gets migrated or when a cart gets removed. And then there is code from other branches and temp debugging code checked in so I think maybe you forgot to push the latest changes?

2021-04-06 06:37 UTC, pozylon commented on packages/api/resolvers/mutations/checkoutCart.js
> +    const order = cart.checkout(transactionContext, {
discard please, await gone, exceptions not catched

2021-04-06 06:37 UTC, pozylon commented on packages/core-products/db/products/helpers.js
> +    `hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh ${JSON.stringify(
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh :)

2021-04-06 06:37 UTC, pozylon commented on packages/core-products/db/products/helpers.js
> +const X = {
rm X

2021-04-06 06:37 UTC, pozylon commented on packages/core-users/db/helpers.js
> +Users.count = async (query) => {
Doesn't this belong to https://github.com/unchainedshop/unchained/pull/342 ?

2021-04-06 10:11 UTC, Mikearaya commented on packages/core-products/db/products/helpers.js
> +    `hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh ${JSON.stringify(
:disappointed: sorry i've forgot

2021-04-06 10:16 UTC, Mikearaya commented
@pozylon you must have missed it ` Orders.ensureCartForUser` gets called in `LoginTokenCreated` handler https://github.com/unchainedshop/unchained/blob/default-user-cart/packages/platform/setup-accounts.js#L69

2021-04-15 10:07 UTC, pozylon requested changes
Everything looks great but we need integration tests for the ENSURE_USER_HAS_CART feature that checks the edge cases in which a user could have no cart. I'd enable ENSURE_USER_HAS_CART in jest-global-setup.js file

2021-04-15 10:14 UTC, pozylon commented
@Mikearaya I have another request, can you extend your new function intializeUsersCart and move Orders.invalidateProviders() from core-orders/orders.js to that new function and also make it configurable, so we can solve https://github.com/unchainedshop/unchained/issues/236#issuecomment-810370355 like I suggested

2021-04-22 09:08 UTC, pozylon commented
Going to merge this without new tests 🤟🎸 we can add those later

2021-05-06 08:31 UTC, merged