Improve Deletion of Products #477
unchainedshop/unchained pull request #522
Opened 2022-11-28 18:22 UTC by Mikearaya

Closes #477

2022-12-06 12:05 UTC, pozylon requested changes

2022-12-06 12:05 UTC, pozylon commented on packages/core-products/src/module/configureProductsModule.ts
> +import { configureQuotationsModule } from '@unchainedshop/core-quotations';
this is not allowed by design (core module can't import from other core modules), find another way please

2022-12-06 12:05 UTC, pozylon commented on packages/core-products/src/module/configureProductsModule.ts
> +import { configureQuotationsModule } from '@unchainedshop/core-quotations';
see removeProductService.ts for reference

2022-12-06 13:10 UTC, pozylon commented
@Mikearaya i just merged master into this pr because there were some conflicts, make sure to pull

2022-12-07 14:44 UTC, pozylon reviewed
Okay while technically this implementation works, i'm having a bit of a problem with the exception concept here and I think the denial checks should be on the top level, why?

1. The removeProduct service is called by the removeProduct mutation and is also called by the bulk import. The bulk import should be more brute force and basically just work so there should not be any errors. But currently both the callee "removeProductService" and the callee of the callee "module.products.delete" throw errors. The only situation when removing a product failed from the point of view of the bulk import was when the product was already removed and in that situation, it's just getting logged to bulk import work and does not have any negative effect on the whole bulk import.

2. Routing the string errors from inside the services and core to the mutation and rethrowing with typed error adds bloat and even removes crucial details that are important, actually when receiving an error in the UI I should be able to parse the conflicting bundle when removing a simple product from a bundle.


Suggestions:
1. Do all checks directly in the mutation but add the functions to check for those issues 
2. Don't just check for `enrollmentExistsForProduct` but use something like `openEnrollmentsWithProduct` and `bundlesWithProduct` then throw the first blocking productId so the error is thrown like this: throw new ProductLinkedToActiveVariationError({ productId, configurableProductId });

2022-12-07 14:44 UTC, pozylon commented on packages/core-products/src/module/configureProductsModule.ts
> +      const activeLinks = await Products.findOne(
Some checks are here...

2022-12-07 14:44 UTC, pozylon commented on packages/core-products/src/service/removeProductService.ts
> +      const hasActiveQuotations = await modules.quotations.quotationExistsForProduct({ productId });
and some are here...

2022-12-07 14:44 UTC, pozylon commented on packages/api/src/resolvers/mutations/products/removeProduct.ts
>    if (!(await modules.products.productExists({ productId })))
and some checks are here...

2022-12-07 14:45 UTC, pozylon commented
reasoning why a bulk import should be able to remove a product that is part of an active bundle is that the bundle removal event could be part of the same batch but comes after.

2022-12-07 21:25 UTC, pozylon requested changes

2022-12-07 21:25 UTC, pozylon commented on packages/core-products/src/module/configureProductsModule.ts
> +      };
Strongly suggest to make 2 functions, this is mixing stuff that has no relation to each other

2022-12-08 05:48 UTC, Mikearaya commented
I merged bundle and proxy query into one to save DB requests and that is the same reason I queried for the single product instead of a list. (firstActiveProductProxy)

2022-12-09 12:02 UTC, pozylon commented
@Mikearaya ok i see that, i think if it were a query that would have to be something to think of but mutations are usually triggered from users and we can afford 300ms

2022-12-09 12:26 UTC, Mikearaya commented
@pozylon  It's ready though, i've separated them

2022-12-09 19:52 UTC, merged