User deletion
unchainedshop/unchained pull request #581
Opened 2023-10-31 20:19 UTC by Mikearaya

2023-11-02 19:39 UTC, Mikearaya commented
don't mind the access control on deleteAccount API but  Should information about the user in order be masked such as `contact` and `billingAddress`?

2024-04-30 21:32 UTC, pozylon commented
@Mikearaya rebase

2024-06-05 17:57 UTC, pozylon commented
@Mikearaya rebase

2024-06-12 12:01 UTC, pozylon commented
I've rebased this again so it's compatible for a merge after localization changes

2024-06-12 12:11 UTC, pozylon requested changes
- Remove enableRightToBeForgotten setting, due to international policies that should be the default and we want to be privacy friendly too. Every user should be able to delete him/herself

Then a general thing:
Order Data should stay immutable. Because of some laws it's usually required to keep users but delete user data. Thus we shouldn't delete orders and such but rather anonymize. What if we just delete all the profile data of the user:
- username
- services/password 
- e-mail from the user 
- last contact, heartbeat, IP's, last billing address
- avatar

Also, keep the reviews. Frontends then can decide to show the review of the user under some name like "Unknown User" or "Deleted User"

2024-06-12 12:11 UTC, pozylon commented on packages/api/src/schema/mutation.ts
> +      deleteAccount(userId: ID): Boolean!
I don't like the naming "account" because we haven't used account across the whole system yet for API's. what about: 
- deleteUser ?

2024-08-19 08:01 UTC, pozylon commented
@Mikearaya we still need this feature but the branch has forked off far away from master now, i tried to rebase/merge but i think the easiest way is to generate a diff file based on the last ancestor (b827dbee) and then manually add the changes to a new branch based on master 🤪

2024-08-19 08:16 UTC, Mikearaya commented
@pozylon agreed, i'll recreate it based on v2.x

2024-08-19 20:41 UTC, closed without merging